hosts:
    uberspace:
        HostName: sabic.uberspace.de
        User: citrus
        
    lemon:
        HostName: lemon.nd-com.net
        User: nd
        Inherits: ipv6
        
    pomelo:
        HostName: pomelo.nd-com.net
        User: nd
        Inherits: ipv6

templates:
    ipv6:
        Gateways:
        - direct
        - uberspace
    
defaults:
    HashKnownHosts: yes
    VerifyHostKeyDNS: ask
    VisualHostKey: yes
    AddKeysToAgent: yes
    UseKeychain: yes
    
    Hooks:
        # Automatically backup ~/.ssh/config
        BeforeConfigWrite:
        - 'exec set -x; cp {{.SSHConfigPath}} {{.SSHConfigPath}}.bkp'
        
        AfterConfigWrite:
        # Alert me with a Desktop notification
        - notify "{{.SSHConfigPath}} has been rewritten"
        
        OnConnect:
        # Alert me with a Desktop notification
        - notify New SSH connection to {{.Host.Prototype}} at {{.Stats.ConnectedAt}}
        # Write the host prototype to the terminal stderr
        - write New SSH connection to {{.Host.Prototype}}

        OnDisconnect:
        # write on terminal and in a Desktop notification some statistics about the finished connection
        - "write  SSH connection to {{.Host.HostName}} closed, {{.Stats.WrittenBytes }} bytes written in {{.Stats.ConnectionDuration}} ({{.Stats.AverageSpeed}}bps)"
        - "notify SSH connection to {{.Host.HostName}} closed, {{.Stats.WrittenBytes }} bytes written in {{.Stats.ConnectionDuration}} ({{.Stats.AverageSpeed}}bps)"

