hosts:
    uberspace:
        HostName: citrus.uber.space
        User: citrus
        
    lemon:
        HostName: lemon.nd-com.net
        User: nd
        Inherits: ipv6
        
    pomelo:
        HostName: pomelo.nd-com.net
        User: nd
        Inherits: ipv6
    
    limetta:
        HostName: limetta.nd-com.net
        User: pi
        Inherits: ipv6
    
    beka-gateway:
        HostName: gateway.beka-software.at
        User: dev
        LocalForward:
        - 50100 192.168.10.51:3389
        - 50200 192.168.10.52:3389
        - 1433 192.168.10.52:1433

templates:
    ipv6:
        Gateways:
        - direct
        - uberspace
    
defaults:
    HashKnownHosts: yes
    VerifyHostKeyDNS: ask
    VisualHostKey: yes
    AddKeysToAgent: yes
    UseKeychain: yes
    
    Hooks:
        # Automatically backup ~/.ssh/config
        BeforeConfigWrite:
        - 'exec set -x; cp {{.SSHConfigPath}} {{.SSHConfigPath}}.bkp'
        
        AfterConfigWrite:
        # Alert me with a Desktop notification
        - notify "{{.SSHConfigPath}} has been rewritten"
        
        OnConnect:
        # Alert me with a Desktop notification
        - "notify New SSH connection to {{.Host.Prototype}} at {{.Stats.ConnectedAt}}"
        # Write the host prototype to the terminal stderr
        - "write New SSH connection to {{.Host.Prototype}}\n"

        OnDisconnect:
        - "notify SSH connection to {{.Host.HostName}} closed, {{.Stats.WrittenBytes }} bytes written in {{.Stats.ConnectionDuration}} ({{.Stats.AverageSpeed}}bps)"
        - "write SSH connection to {{.Host.HostName}} closed, {{.Stats.WrittenBytes }} bytes written in {{.Stats.ConnectionDuration}} ({{.Stats.AverageSpeed}}bps)\n"

